### ISSUE TITLE
 can i use indicate in vue project?

### ISSUE THREAD

**Issue by zhouyou-az** [tobua/indicate#1]

**Comment by zhouyou-az** [comment]
My project that creates with VUE CLI.I try to import indicate, but failed.

**Comment by tobua** [comment]
Hey @zhouyou-az 

I'm currently finishing up the 3.0 release (complete rewrite). I don't know whether it will work with vue, but will try once 3.0 is released (probably this weekend). Personally, I have no experience with vue, but maybe I'll add a dedicated vue plugin soon.

Will keep you updated.

**Comment by zhouyou-az** [comment]
Fine@tobua 
I appreciate the effort you put in.

**Comment by tobua** [comment]
@zhouyou-az quick update:

Version 3 of the plugin has just been released and I've tried it with vue and it seems to work well. There are some notes and a working example in [plugins/vue](https://github.com/tobua/indicate/tree/master/plugins/vue). Basically the plugin can be integrated like any other vanilla JS plugin.

Hope this helps if you're still looking for a plugin like this.
